### ISSUE TITLE
No repository is displayed

### ISSUE THREAD

**Issue by gabriel-vanca** [coenm/RepoM#145]
None of the repositories are displayed.

I've tried to debug the problem, the paths are loaded correctly, but then nothing gets displayed.

Also sometimes the app crashes after it loads somehow a null observer object in the array, but not always.

**Comment by coenm** [comment]
Hi @gabriel-vanca 

Thanks for trying RepoM. 

I'm willing to help but I need more information.

1. Are you running RepoM using the installer or are you building and running from source?
1. Can you list the filenames in the `%AppData%\RepoM` directory?
1. `%AppData%\RepoM\appsettings.json` contains one setting (`ReposRootDirectories`) to edit manually. Can you make sure you set at least one directory to scan using the following 'syntax' (with ending backslash and it's best to have the casing correct):
  
```yaml  
  "ReposRootDirectories": [
    "C:\\Projects\\",
    "C:\\Repositories\\",
  ],
```

1. Make sure you enable the plugin `LuceneQueryParser`. This can be done using the UI but also by editing the `appsettings.json` again.
```yaml
 "Plugins": [
    ...
    {
      "Name": "LuceneQueryParser",
      "DllName": "RepoM.Plugin.LuceneQueryParser.dll",
      "Enabled": true
    },
    ...
```

Do not edit `appsettings.json` when RepoM is running.

1. Is there a logfile created in `%AppData%\RepoM\Logs` and does it help?
1. When repositories are found, these will be stored in a cache located at `%AppData%\RepoM\Repositories.cache`. Is this file created and does it contain full paths of expected repositories?

### Workaround

I'm aware that RepoM is not fully stable when starting for the first time (or when it doesn't have any repos found). I've seen problems with the Observer before. I suggest that after starting RepoM, you do not open it for a while (10 minutes) such that it can find and process repositories.
- When it not crashing, all found repositories should have been listed in the `Repositories.cache`. Also review the logs if you see exceptions.
When you don't see any repositories, it might have something to do with the filtering of RepoM (not realy documented yet)

- When RepoM crashed, review the logs and review the settings.

I can help in both cases but lets first find out what is happening.

**Comment by gabriel-vanca** [comment]
1. Both. Same thing happens.
2. File names in `%AppData%\RepoM` are:
![image](https://github.com/user-attachments/assets/e4207c4f-79ff-4e4f-897b-9578fdab8a83)
3. I've added the root directories, but this really shouldn't be necessary.
4. It's enabled.
5. Log file is huge (417kb). I've deleted it and restarted RepoM. It seems to be ignoring the Root Repository Setting; it finds all the repos in my computer and proceeds with creating observers for them. I only see one error, on the 2nd line of the new-ly made log file, just been `Started` and `Monitor.Observe starting` : 

```
Could not connect to Vss. Module will not be enabled.
System.ArgumentNullException: Value cannot be null. (Parameter 'baseUrl')
   at Microsoft.VisualStudio.Services.Common.ArgumentUtility.ThrowArgumentNullException(String paramName)
   at Microsoft.VisualStudio.Services.WebApi.VssConnection..ctor(Uri baseUrl, VssHttpMessageHandler innerHandler, IEnumerable`1 delegatingHandlers, Boolean allowUnattributedClients)
   at Microsoft.VisualStudio.Services.WebApi.VssConnection..ctor(Uri baseUrl, VssHttpMessageHandler innerHandler, IEnumerable`1 delegatingHandlers)
   at Microsoft.VisualStudio.Services.WebApi.VssConnection..ctor(Uri baseUrl, VssCredentials credentials, VssHttpRequestSettings settings)
   at Microsoft.VisualStudio.Services.WebApi.VssConnection..ctor(Uri baseUrl, VssCredentials credentials)
   at RepoM.Plugin.AzureDevOps.Internal.AzureDevOpsPullRequestService..ctor(IAzureDevopsConfiguration configuration, ILogger logger)
```

6. Yes, the `Repositories.cache` correctly lists all the repositories.
7. Yes, you're right. It was the filters! It was set by default to Work. It works fine on Private or Default. I suggest Default should be the actual default 😃 
8. It's still ignoring the `ReposRootDirectories` until I clicked the Clear button. It seems the repositories outside of ReposRoot remain in the Cache file even if Scan is pressed and only Clear clears it. This is confusing. I suggest these are replaced with `Fast Scan` (only scans for new ones) and `Full Scan` (clears and scans).
9. Both the installed and the built from source one seem to work well now. I did actually notice that with the original RepoZ, it would not list the "Start from Visual Studio" -type actions when I'd build from source.
10. Building from source, I can also see the following errors in the debugger:
```
- Exception thrown: 'System.IO.IOException' in PresentationFramework.dll
- Exception thrown: 'System.ArgumentNullException' in Microsoft.VisualStudio.Services.Common.dll
- Exception thrown: 'System.InvalidOperationException' in System.Private.CoreLib.dll
- System.Windows.Data Warning: 4 : Cannot find source for binding with reference 'ElementName=captionGrid'. BindingExpression:Path=ActualHeight; DataItem=null; target element is 'RowDefinition' (HashCode=27262282); target property is 'Height' (type 'GridLength')
- DefaultRepositoryMonitor.cs(100,21,100,89): warning CS4014: Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call.
- DefaultRepositoryMonitor.cs(304,9,304,132): warning CS4014: Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call.
- Combridge.cs(43,13,43,54): warning CA1416: This call site is reachable on all platforms. 'Marshal.FinalReleaseComObject(object)' is only supported on: 'windows'. 
- ExplorerWindowActor.cs(13,35,13,78): warning CA1416: This call site is reachable on all platforms. 'Type.GetTypeFromProgID(string)' is only supported on: 'windows'.
- MainWindow.xaml.cs(676,24,676,50): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
```
