### ISSUE TITLE
NullRef exception in Reset()

### ISSUE THREAD

**Issue by gabriel-vanca** [coenm/RepoM#160]
NullRef exception is thrown in Reset() upon pressing the Clear button.

![image](https://github.com/user-attachments/assets/31144f0a-bdb5-4fa7-baf5-de8f4de1ad26)

The repo collection seems to contain one null element.

![image](https://github.com/user-attachments/assets/29c8903f-5ca3-4f6a-8268-21a7e1e67600)

⚠️  This can obviously be easily fixed with a NULL check (I will create a pull request for that soon), but further investigation is required to determine what causes the Null element to be added. Maybe a JSON parsing error when reading the file from the cache?

**Comment by coenm** [comment]
I'll close this issue after merging the PR.
