### ISSUE TITLE
Does WindowsExplorerTitle still work?

### ISSUE THREAD

**Issue by gabriel-vanca** [coenm/RepoM#167]
Does WindowsExplorerTitle actually do anything? I don't see it changing anything in Windows Explorer when I am in a git repo.

**Comment by coenm** [comment]
Depends on your Windows version. When I used Windows 10, it showed the branch name in the title like RepoZ.
Now, running on Windows 11, in only shows when hovering over the explorer icon in the start bar at the bottom:

![image](https://github.com/user-attachments/assets/ca966f4d-2827-401e-af82-1b63d4cf48cd)


I don't have the plugin enabled anymore. It would be nice if it is possible to alter the title bar of the Explorer Window again.

**Comment by gabriel-vanca** [comment]
Doesn't seem to work anymore on Windows 11 24H2:

![image](https://github.com/user-attachments/assets/be48cfb3-9d39-43ff-9411-75d297a37f84)

![image](https://github.com/user-attachments/assets/00f0a8ca-c9f5-460e-a0cd-149a8b535146)
