### ISSUE TITLE
Date broken

### ISSUE THREAD

**Issue by gabriel-vanca** [coenm/RepoM#183]
I'm not entirely sure what the date for each repo is meant to show, but either way it seems to be broken.

![image](https://github.com/user-attachments/assets/9cbd9671-67df-4cd8-bb2f-3b8c262892ef)

It seems to show either the time RepoM started or "one hour ago" which seems to be caused by it taking UTC time, not local time (BST) (hence always one hour difference).
It also often shows "Just now" despite me not having done anything in several tens of minutes to a repo.

**Comment by coenm** [comment]
I looked into the code, it shows (in a user friendly manner) when this repository item (`RepositoryViewModel`) was created, which in turn implies when the repository had it's last 'update'.

I think this needs some attention, or deletion

**Comment by gabriel-vanca** [comment]
Yes, which is a shame as it could've been helpful to see when the repo last had a commit/activity. I don't know if Lib2Git can show that. maybe worth looking into it? It can also help with sorting the repos. And probably better not to show it as a tooltil, but as a full textblock (just right of 'github')
