### ISSUE TITLE
[Code Restyle] [Suggestion] Reduce number of Plugins

### ISSUE THREAD

**Issue by gabriel-vanca** [coenm/RepoM#191]
I think the following plugins should just be merged into either Api or Core project:

- Clipboard - too simple to be a plugin on its own.
- WebBrowser  - too simple to be a plugin on its own
- Statistics - core app functionality. App often crashes without it as Ordering depends on it.

I get it that the point of plugins is to make the core app more lightweight, but that doesn't work if we have to add too much error-checking for cases where we have to check whether a necessary plugin is enabled or not (such as with Statistics).

**Comment by coenm** [comment]
I like it to be plugins as users can enable or disable them, although I'm aware of both the Clipboard and Webbrowser are very light and simple

It is true that when statistics is not enabled and the Sort yaml or Order yaml has parts that depend on statistic features it crashes.
This is more related to #172, #156, and #95 
Also linked to #173

For now, I'm more interested in how RepoM should handle valid yamls using disabled plugins on yaml configurations based
