### ISSUE TITLE
Cannot debug while RepoM is on

### ISSUE THREAD

**Issue by gabriel-vanca** [coenm/RepoM#200]
As the new update enforces a single RepoM instance, it is no longer possible to debug while RepoM is on.

**Comment by coenm** [comment]
Yes, RepoM enforces only one single instance to run and I can imagine this is not very nice when developing.  I just close RepoM when developing but this is not optimal

Possible solutions:
- Running in 'debug' doesn't use a mutex (or de different one).
- Based on the configuration location, a different lock is used.

The first one is easier, the second one is imo nicer.

**Comment by gabriel-vanca** [comment]
> Running in 'debug' doesn't use a mutex (or de different one).

Yes, this is also what I had in mind.
